### ISSUE TITLE
Implement "search" on "playlists"

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#10]
- [x] implement playlists
- [ ] implement search by tag [i.e. the dropdown list should filter the results]

**Comment by jellegerbrandy** [comment]
questions:

 * how does search work? Tags? @lupape 
 * do we have some sample material we can use?

**Comment by felipegaucho** [comment]
@jellegerbrandy there's some sample material we can use here: https://wdrv.it/2393d6880
It can be under a playlist named "Around the Block", tagged as you wish.

As for the search mechanism, I think we should have search by playlists, by tags, and a sorting filter. Something like this:

![arquivo 07-07-17 18 57 02](https://user-images.githubusercontent.com/26517120/27978783-e0504e74-6347-11e7-88e3-5c9434897033.jpeg)

By the way, I think the tab should be named 'Videos' or 'Watch' or 'Browse', instead of 'Playlist'.

**Comment by lupape** [comment]
No way 3 box search. The ideia are the system showing the best
correlaction. Similar when you search on youtube. When the user receive the
result than he can filter with keywords, most recent and other. But for
now, we going just with fixplaylist without search.

Em 7 de jul de 2017 19:10, "Felipe Sant Ana" <notifications@github.com>
escreveu:

**Comment by pedrocasa** [comment]
@jellegerbrandy  Right now I'm finishing this flow, later on, I want to create a wiki with every single page 

[FLOW-MINI.pdf](https://github.com/Paratii-Video/paratii-player/files/1388970/FLOW-MINI.pdf)

**Comment by pedrocasa** [comment]
My Idea was to search for a playlist on the search page, just like youtube.
And leave the playlist page only for your playlists ( like youtube, spotfy etc )

**Comment by geckoslair** [comment]
Close in favor of: #165
