### ISSUE TITLE
How does the user recover the password?

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#130]
I'm having a bit of difficulty creating the "forgot your password" pages. I would like to know step by step how the user retrieves the password.
@jellegerbrandy 

-We are talking here about the situation described in https://github.com/Paratii-Video/paratii-player/issues/105, the login moment:

- **1 (login)** - Text:"Log in". 2 fields (email, password) and buttons (log in, sign up, forgot pass?).
- **1.a** Click "sign up* -> open new model **3**
- **1.b** Click "log in" -> if no keystore is found, go to 5. 
- **1.c** Click "forgot password" -> open new modal **2**

- **2 (forgot password)** field (email [can come filled from previous screen]) and button (send me a reset link)
- **2.a** - If clicks send me a reset link, tell him "We sent you a reset link. Check your email!"
- **2.b** - If clicks on the link on the email, goto to **(4)**
- **3 (sign up)** 3 fields: username, email, password, confirm password. (like the present signup form, but as a modal). Click submit. If data are ok, go to **3.a**
- **3.a.*** show the user the 12 words, with some text reminding him to save this info
- **4 (reset password)** (user arrived here from the "reset password" link). Show the email; two fields: password and confirm password. Next go to **5**
- **5 (restore keystore)**: field "12 magic words", button "submit". On submit:
- **5.a. (12 words invalid)**: if generated account does not match account associated with the email
- **5.b. (12 words ok)**

**Comment by jellegerbrandy** [comment]
The user never "recovers" his password - he is the only one who knew it. But we can reset it.

The password is used for (1) logging in to meteor and (2) for unlocking the local keystore that you need to interact with the blockchain. 
To reset your password, the user needs to re-create the local keystore *on all your devices* with the 12 word password.

I'd say the flow for forget password is something like this:

 1. Click on "forgot your password"? --> [optional: insert a "we wills end you a reset link"] --> Go to a new modal with "new password", "confirm new password"  --> (you are now logged in but cannot access yr old keystore) Insert 12 magic words to regenerate your wallet --> DONE

Another case is where you cannot access a local keystore with an existing account,  either because (a) you reset your pass on another device, and on this device, the keystore is encrypted with the old password or (b) it's a new device and has no keystore yet. 

What we need to do in these cases is to ask the user for the 12-word phrase to (re)generate the local wallet. It makes most sense to ask immediately after login for the 12-word phrase.

see also https://github.com/Paratii-Video/paratii-player/issues/105

**Comment by jellegerbrandy** [comment]
@eliawk @enricocicconi

**Comment by jellegerbrandy** [comment]
We are talking here about the situation described in https://github.com/Paratii-Video/paratii-player/issues/105, the login moment:

- **1 (login)** - 2 fields (email, password) and buttons (log in, sign up, forgot pass?).
- **1.a** Click "sign up* -> open new model **3**
- **1.b** Click "log in" -> if no keystore is found, go to 5. 
- **1.c** Click "forgot password" -> open new modal **2**

- **2 (forgot password)** 2 fields (email [can come filled from previous screen]) and buttons (restore wallet, send me a reset link)
- **2.a** - If clicks send me a reset link, tell him "We sent you a reset link. Check your email!"
- **2.b** - If clicks on the link on the email, goto to **(4)**
- **3 (sign up)** 3 fields: username, email, password, confirm password. (like the present signup form, but as a modal). Click submit. If data are ok, go to **3.a**
- **3.a.*** show the user the 12 words, with some text reminding him to save this info
- **4 (reset password)** (user arrived here from the "reset password" link). Show the email; two fields: password and confirm password. Next go to **5**
- **5 (restore keystore)**: field "12 magic words", button "submit". On submit:
- **5.a. (12 words invalid)**: if generated account does not match account associated with the email
- **5.b. (12 words ok)**

**Comment by pedrocasa** [comment]
@jellegerbrandy great work
I just have one doubt, if the 12 words are invalid (5.a) the user can ask for a reset link ( like 2.a) ?

**Comment by pedrocasa** [comment]
@jellegerbrandy great work
If the 12 words are invalid (5.a) the user can ask for a reset link ( like 2.a) ?

**Comment by jellegerbrandy** [comment]
No, without the 12 words, the account is lost. The user can either try to recuperate the 12 words from another device, or, failing that, needs to generate a new address.

**Comment by pedrocasa** [comment]
- What does the "restore button " do?

**Comment by pedrocasa** [comment]
- what is the second field on the forgot password modal ?
- What does the "restore button " do?

**Comment by jellegerbrandy** [comment]
Oh, Perdro, I'm sorry for the cunfusion: I had started a comment on this issue (which you read) but then thought it would be better to change the issue itself. So just read the top (there is no second field or "restore" button in step (2))

**Comment by jellegerbrandy** [comment]
Please see https://github.com/Paratii-Video/paratii-player/issues/248 for an alternative solution. Closing this for now.
