### ISSUE TITLE
Design.Mini Playlist M17-M26 

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#163]
Issue for playlist pages discussion.
( M17-M26 )

Give me your feedback about the layout and functionality.

- If you need to refer to a certain page, write the number of the page you are referring to.
- Not every page is in this flow, check the others Design.Mini issues

[flow-playlist.pdf](https://github.com/Paratii-Video/paratii-player/files/1408856/flow-playlist.pdf)

**Comment by felipegaucho** [comment]
### Few things I noted:
- **Screen name** Playlist -> Playlist**s** (better, no?)
- **Search field** missing still, and resulting screen for the search, which shouldn't differ much from main screen (search field on the top?).
- Just to make it clear: purchased videos should be created only if the user has purchased a video, watch later only if he's marked one video as such. Otherwise, there's just the dotted box on the first row (right @pedrocasa ?)
- Should there be also an option of **"playing the playlist"** (instead of opening it to play individual vids?) It can be a bigger play somewhere that does one video come up after the other... Shouldn't be tough, right?
- How to scroll to the right? In M17, for example, if the user has himself 4-5 playlists, how to get to the 5th?

### Details:
- On M22 there's _playlist_ (non-capital p) and _Playlist_ (capital P) -> standardise.
- Fine with M24's title being capitalised - if it's standard for "removal" or "non-reversible-actions" modals.
- Prices in the etiquettes: in PTI, not U$ (for now).
- On M20 and M23 I feel options have weird spacing between them (should be standardised, there's other checkbox list somewhere with smaller spacing).

### Optionals which I think are doable (lmk):
- **Follow playlist ("subscribe")** option. We don't have this yet, and I think @peFor now, when clicked, could just make the playlist go to the "my playlists"on the playlist page (maybe w/ something slightly different, a discreetly different shadow or something - don't know). So in the future we can easily add a staking function to it, and transpose Token Curated Registries to playlists, make ownership collective, etc
- **Creator of playlist** doesn't show up anywhere. Can be just "By XXXX", as in the "paused video" screen? Is it important"
- **Share playlist** is not possible yet. Should there be a share icon somewhere, that can simply copy a link to clipboard?

Note: we have no playlist descriptions still. **Fine for now, though.**
Note 2: we have no ordering of videos inside playlists still. **Fine for now, though.**

**Comment by pedrocasa** [comment]
- Search Field: My idea was to leave all the search process exclusively on the M54-M58 pages,  It doesn't matter if it is a playlist, a video or a channel/user ( same flow used on youtube, Spotify, Vimeo ... ). 
If the advantage of having a search field on the playlists page is to search only playlists we can design more options on the page M57.

- There's no side scroll, if you add a new playlist it will be like it >> 
![capture_01](https://user-images.githubusercontent.com/30123644/31723670-49bbdeb2-b3fe-11e7-87cc-2abbd728b388.JPG)

The suggested playlists can be replaced under it or disappear after the user create a new playlist

**Comment by jellegerbrandy** [comment]
+1 for having one general search field that works the same everywhere you encounter it (i.e. no separate "search for playlists" or something). I think it should not be separate from the playlists, though., https://github.com/Paratii-Video/paratii-player/issues/165#issuecomment-337534830

**Comment by pedrocasa** [comment]
- re-uploaded flow
- I still haven't found a way for the user to subscribe to a playlist
