### ISSUE TITLE
Back button wrong behaviour

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-player#285]
### Description:
back button should no trigger a history back.

`
Template.backButton.events({
  'click #back-button' () {
    window.history.back()
  }
})
`

#### Steps to Reproduce:

1. go to google
2. then go http://localhost:3000/playlists/2
3. then press on play list back button
4. user return to google

#### Expected result:

return to playlists list

**Comment by jellegerbrandy** [comment]
I propose to **remove the back button**
Because (1) it is not clear at all that it _is_  a back button (if I wanted to "go back", I would not think of clicking on the "<" next to the title) and (more importantly) (2) I don't understand in which case this is something that a user wants/needs/expects.
@pedrocasa , what do you think?
