### ISSUE TITLE
Refactor the player and use a standard library

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#306]
This is a dicussion topic, with info so we can make the best decision.

Up to now, we have more or less hacked our own player. We now have a good idea what we need, so we can look for frameworks/libs that can help us standardize/make robust/hook in to a community. Clappr is one option for that. Are there other options?

| what | github url | github contribs and last commit | minified size | cool site? | docs? |  plugins | subtitle plugin? | hls support | remarks    | 
|------|------------|---------------------------------|------------|------------|---------|-------|------------------|-------------|------------|
|  [Clappr](http://clappr.io/)  | [clappr/clappr](https://github.com/clappr/clappr) | active, 60 contribs, 4K stars | 464Kb | pretty cool but not functional  |  okayish (tutorial?) | many plugins | Y | Y |  
| [videojs](http://videojs.com/)  | [videojs](https://github.com/videojs) | 274 contribs, active, 20K stars | 243Kb | yes |[docs](http://docs.videojs.com) | **many** |  Y | Y | check this out: http://videojs.com/advanced/
| [mediaelement](http://www.mediaelementjs.com/) | [mediaelement](https://github.com/mediaelement/mediaelement)  | 200 contribs, 5.5K starts, active | 67Kb* | ugly site | Ok docs | yes, but not so many |  No (?) | ? | 
| https://plyr.io/ |  

All these have liberal OS licenses - MIT, Apache.
'*' size doesn't include all needed parts, A full installation probably require a whole lot more dependencies.

**Comment by ya7ya** [comment]
I been looking at player frameworks we could use, so here are few points we need
to have in any framework we end up using , or creating or own.

1. **Extensible** : This need to extend it to include features easily and in a modular
way.
2. **Modular**: so we can shave fat off the player.
3. **cross-browser/device**: has to work on all devices outta the box.
4. **Active Community**: Because if it's dead or old, I'd rather start from scratch.
5. **Docs**: well documented.

I'm currently looking at video.js and clappr.js, mediaelement seems old and fits
better with a php stack (wordpress).

## My Current Goals

1. [ ] has to work independently from Meteor.
2. [ ] integrate paratii-IPFS seamlessly.
3. [ ] passes the playerjs test.

**Comment by jellegerbrandy** [comment]
Decided in clappr, development continues in https://github.com/Paratii-Video/paratii-mediaplayer
