### ISSUE TITLE
Design.Loading page

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#376]
Hey guys,

Junior suggested that we treat the loading pages in the same way as the error warnings, generic and modular. 
So I made this diagram explaining what would happen if we need to remove/add information

![loading](https://user-images.githubusercontent.com/30123644/33888871-7c95f4f0-df35-11e7-9d25-52ba09de1b0d.png)

**Comment by jellegerbrandy** [comment]
I would definitiel forget about the "duplication rate" there, which is a difficult concept, and who cares (apart from us programmers, I mean)

Information we have that is interesting to the user:

  * number of connected peers
  * (also: who are you connected to, but that won't fit here)
  * total downloaded (i.e. 1.23 Mb)
  * download speed (3400kb/s)
  * total uploaded
  * upload speed

I think here the number and the totals are very important (totals will serve for accounting), but the speed as well.

We can save some space because we will never have those "extreme values" for download speed (123456789kB/s we will write as 1.23Gb/s, and we have at most 100 connected peers. So perhaps we can have texts like:

  * **download:** 1.3Mb of 3.2Mb at 0.45Mb/s
  * **upload:** 3.44Mb at 123Kb/s
  * You are connected to **4** peers
