### ISSUE TITLE
upgrade to Iron Router

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#71]
https://kadira.io/ has closed, and so it would not be a bad idea to change. Ironrouter is the alternative: https://github.com/iron-meteor/iron-router

**Comment by brenopolanski** [comment]
I was migrating to Iron Router and realized that it is a bad idea to do this now, because Iron Router has some problems and it is not either actively updated.

In Iron Router you can use reactive content inside the router, but any hook or method can re-run in an unpredictable manner. FlowRouter limits reactive data sources to a single run; when it is first called.

At least for now, I feel the approach and ideology of Flow Router is much more conducive to well written applications, as it allows the developers, new and old, to focus their code and be clear with what they are doing and why.

On Paratii player we should think about them as compositions of independent components. Looking across the interface, we can see a handful of components. So a good chose is use React instead of Blaze, and then we could migrate from FlowRouter to [react-router](https://github.com/ReactTraining/react-router). It does not have to be done now, but it's a thing to think about.

**Comment by jellegerbrandy** [comment]
ok, good points, closing the issue.
